-- 코드를 작성해주세요
select s.ROUTE, 
CONCAT(ROUND(SUM(s.D_BETWEEN_DIST),1),'km' )as TOTAL_DISTANCE,
CONCAT(ROUND(AVG(s.D_BETWEEN_DIST),2),'km') as AVERAGE_DISTANCE
from SUBWAY_DISTANCE as s
group by s.ROUTE
order by SUM(s.D_BETWEEN_DIST) DESC